name: build

on:
  pull_request:
  push:

jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.14.14
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          targets: linux/386,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          race: false
          buildmode: default
      -
        name: list artifacts
        run: |
          ls -ahl ${GITHUB_WORKSPACE}/build/*
