name: release

on:
  create:

jobs:
  xgo:
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - 1.14.14
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: ${{ matrix.go_version }}
          dest: build
          targets: linux/386,linux/amd64,linux/arm64,darwin/amd64
          v: true
          x: false
          race: false
          buildmode: default
      -
        name: list artifacts
        run: |
          ls -ahl -R ${GITHUB_WORKSPACE}/build
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/github.com/infinityworks/github-exporter-*"
          token: ${{ secrets.GITHUB_TOKEN }}
